---
- name: Deploy Docker container on EC2 instances
  hosts: all  # Specify the group of EC2 instances you want to deploy to

  tasks:
    - name: Update package cache
      become: true
      apt:
        update_cache: yes
      tags: update_cache

    - name: Install Python
      become: true
      apt:
        name: python3-pip
        state: present
      tags: install_python

    - name: Start Docker Service
      become: true
      service:
        name: docker
        state: started
      tags: start_docker_service

    - name: Pull Docker image
      become: true
      shell: docker pull hazelnelthropp/hazel-pro:v2
      tags: pull_docker_image

    - name: Run Docker container
      become: true
      shell: docker run -itd -p 5000:5000 hazelnelthropp/hazel-pro:v2
      tags: run_docker_container
