- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt package lists
      apt:
        update_cache: yes

    - name: Install Python
      apt:
        name: python3-pip
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Deploy the image and Run as a container
      command: docker run -itd -p 5000:5000 kranthi619/hazel-pro:v1
